name: Release Helm Chart

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Update Chart version and appVersion
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          sed -i "s/^version:.*/version: ${VERSION}/" helm/prunarr/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: \"${VERSION}\"/" helm/prunarr/Chart.yaml

      - name: Lint Helm chart
        run: helm lint helm/prunarr

      - name: Package Helm chart
        run: helm package helm/prunarr

      - name: Upload chart to release
        uses: softprops/action-gh-release@v1
        with:
          files: prunarr-*.tgz

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ${{ env.REGISTRY }} --username ${{ github.actor }} --password-stdin

      - name: Push chart to GHCR
        run: |
          helm push prunarr-${{ steps.version.outputs.version }}.tgz oci://${{ env.REGISTRY }}/${{ github.repository_owner }}/charts
